/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
} from '@stencil/router';


export namespace Components {

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppProfile {
    'match': MatchResults;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface JpFooter {}
  interface JpFooterAttributes extends StencilHTMLAttributes {}

  interface JpHeader {}
  interface JpHeaderAttributes extends StencilHTMLAttributes {}

  interface JpNavPrimary {}
  interface JpNavPrimaryAttributes extends StencilHTMLAttributes {}

  interface JpNavSecondary {}
  interface JpNavSecondaryAttributes extends StencilHTMLAttributes {}

  interface JpRacingStripe {}
  interface JpRacingStripeAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppHome': Components.AppHome;
    'AppProfile': Components.AppProfile;
    'AppRoot': Components.AppRoot;
    'JpFooter': Components.JpFooter;
    'JpHeader': Components.JpHeader;
    'JpNavPrimary': Components.JpNavPrimary;
    'JpNavSecondary': Components.JpNavSecondary;
    'JpRacingStripe': Components.JpRacingStripe;
  }

  interface StencilIntrinsicElements {
    'app-home': Components.AppHomeAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-root': Components.AppRootAttributes;
    'jp-footer': Components.JpFooterAttributes;
    'jp-header': Components.JpHeaderAttributes;
    'jp-nav-primary': Components.JpNavPrimaryAttributes;
    'jp-nav-secondary': Components.JpNavSecondaryAttributes;
    'jp-racing-stripe': Components.JpRacingStripeAttributes;
  }


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLJpFooterElement extends Components.JpFooter, HTMLStencilElement {}
  var HTMLJpFooterElement: {
    prototype: HTMLJpFooterElement;
    new (): HTMLJpFooterElement;
  };

  interface HTMLJpHeaderElement extends Components.JpHeader, HTMLStencilElement {}
  var HTMLJpHeaderElement: {
    prototype: HTMLJpHeaderElement;
    new (): HTMLJpHeaderElement;
  };

  interface HTMLJpNavPrimaryElement extends Components.JpNavPrimary, HTMLStencilElement {}
  var HTMLJpNavPrimaryElement: {
    prototype: HTMLJpNavPrimaryElement;
    new (): HTMLJpNavPrimaryElement;
  };

  interface HTMLJpNavSecondaryElement extends Components.JpNavSecondary, HTMLStencilElement {}
  var HTMLJpNavSecondaryElement: {
    prototype: HTMLJpNavSecondaryElement;
    new (): HTMLJpNavSecondaryElement;
  };

  interface HTMLJpRacingStripeElement extends Components.JpRacingStripe, HTMLStencilElement {}
  var HTMLJpRacingStripeElement: {
    prototype: HTMLJpRacingStripeElement;
    new (): HTMLJpRacingStripeElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement
    'app-profile': HTMLAppProfileElement
    'app-root': HTMLAppRootElement
    'jp-footer': HTMLJpFooterElement
    'jp-header': HTMLJpHeaderElement
    'jp-nav-primary': HTMLJpNavPrimaryElement
    'jp-nav-secondary': HTMLJpNavSecondaryElement
    'jp-racing-stripe': HTMLJpRacingStripeElement
  }

  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'jp-footer': HTMLJpFooterElement;
    'jp-header': HTMLJpHeaderElement;
    'jp-nav-primary': HTMLJpNavPrimaryElement;
    'jp-nav-secondary': HTMLJpNavSecondaryElement;
    'jp-racing-stripe': HTMLJpRacingStripeElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
